### ISSUE TITLE
HavokActorTool: hkrb naming problem

### ISSUE THREAD

**Issue by Skysaure** [ArchLeaders/HavokActorTool#1]
So i did a bunch of testing an it turns out it the name of the hkrb when i named it FldObj_Test as a test it work but naming it other things cause problems like FldObj_Village_Furnace_A or alot of other things will cause havok to not generate certain files.
![image_2024-09-01_104307015](https://github.com/user-attachments/assets/6f7f22be-49fd-485a-b256-b394f15d32f8)
The working version will create a 
Actorlink
lifecondition
modellist
Physics

The problem now is for alot of names it will only generate 
ActorLink
modellist
Physics

Which i cant open with botw_actor_tool or wildbits and working on development of mods is getting consitently harder and naming it multiple times and it not working for any of them is frustrating if a patch or know fix is possible it would be much appreciated tyy

Edit: this isnt with just one model its with multiple

**Comment by ArchLeaders** [comment]
I'll look into it.

**Comment by ArchLeaders** [comment]
It works fine on my end with the name `FldObj_Village_Furnace_A`, can you send the exact inputs you used?

**Comment by Skysaure** [comment]
"HavokActorTool.exe FldObj_Village_Furnace_A.hkrb -f -n" thats what i use
for everything and all of them work

**Comment by ArchLeaders** [comment]
Alright, I've tracked down the issue.

Currently, HavokActorTool is trying to find an actor with a similar hkrb size to use as the starting actor.

Some of the found actors don't have LifeCondition files, so the script never updates them.

I'll add something to ensure LifeCondition is always added, or build the actor from scratch.

You can workaround this now by setting a base actor (`-b`) to use when creating the actor.

**Comment by Skysaure** [comment]
thank you sm appreciate it i was struggling lol

**Comment by ArchLeaders** [comment]
Should be fixed by https://github.com/ArchLeaders/HavokActorTool/commit/123b23b09a302ba4cd27b0db323812f492251635
