### ISSUE TITLE
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Actor\Pack\

### ISSUE THREAD

**Issue by AdmilZhao** [ArchLeaders/HavokActorTool#3]
Whenever I try to use the tool it gives me this error. I don't know what I am doing wrong

![image](https://github.com/user-attachments/assets/1935bb97-82a6-43b8-88f1-8f876eacf092)

Please help

**Comment by ArchLeaders** [comment]
Make sure you have set your game path in the settings.

**Comment by AdmilZhao** [comment]
Now it's giving me this error
![image](https://github.com/user-attachments/assets/bd206c60-c7e5-41b4-93b3-37edfff882f8)

Sorry for the trouble

**Comment by ArchLeaders** [comment]
Ah, now that may be an error on my end, I'll look into it.

**Comment by AdmilZhao** [comment]
Okay thank you

**Comment by ArchLeaders** [comment]
Ah, I see the issue, change the BaseActorName to nothing. That field is for a vanilla actor name to use when building the custom one.

**Comment by AdmilZhao** [comment]
Hey I'm really sorry to keep bothering you but that didn't seem to work. I'm still getting the same error but now it's just saying this:
![image](https://github.com/user-attachments/assets/2dc0c6bd-0f06-4643-bc4b-af2b03653f14)

I'm really sorry for the trouble

(Sorry for the late reply I wasn't home when you responded so I wasn't able to try your solution until now)

**Comment by ArchLeaders** [comment]
I must have made a mistake when checking the field. Please try restarting the app and avoid filling out that field.

**Comment by AdmilZhao** [comment]
Tried that and it just keeps defaulting to "TwnObj_HunterHouseBed_A_01" whenever I run it for some reason

I am very sorry for the trouble

**Comment by ArchLeaders** [comment]
That is expected behaviour, however, if you update to 2.0.1 you can clear it without an issue.

**Comment by AdmilZhao** [comment]
It's still defaulting but now it's saying this
"System.IO.FileNotFoundException: The actor 'TwnObj_HunterHouseBed_A_01' is not a vanilla actor. Please change the 'Base Actor' field."

Even when I clear it and run it again it just defaults back again

**Comment by ArchLeaders** [comment]
It should default to that because it automatically looks for the best match. However, that actor does exist, so the issue is with your game dump. Possibly the path is wrong, or else the dump is incomplete.

**Comment by AdmilZhao** [comment]
I have the actor in my game directory. What should the path look like so I can verify if I have it right?

Sorry again for the trouble

**Comment by ArchLeaders** [comment]
> I have the actor in my game directory. What should the path look like so I can verify if I have it right?
> 
> Sorry again for the trouble

It depends on where it's stored on your computer, but it should end in `content` (or the folder containing `Actor`, but not the `Actor` folder itself).

![image](https://github.com/user-attachments/assets/3818f82e-d7f2-4944-a130-c1e8bead7ce5)

**Comment by AdmilZhao** [comment]
There we go! Finally! I had the game directory folder wrong I think.

Thank you very much for the help. Sorry it ended up being so complicated

**Comment by ArchLeaders** [comment]
No worries, I'm glad you got it sorted.
